#!/bin/bash
# Generate the boot splash header from any image (JPEG, PNG, ... anything ImageMagick reads).
#
# Usage: scripts/mkbootlogo.sh <input-image> [output-header]
#
# Resizes to fill 240x240 (aspect-preserving, center crop), converts to RGB565 and writes
# a PROGMEM C header that gets compiled into the firmware (no LittleFS space used).
# Rebuild and flash to apply:
#   scripts/mkbootlogo.sh photo.jpg && pio run --target upload
#
# Requires: ImageMagick (magick), python3.
# Output: a header defining `static const uint16_t BOOT_LOGO_RGB565[LCD_W * LCD_H] PROGMEM`
# in standard RGB565 (R high), matching LCD_RED=0xF800 so the splash needs no byte swap.

set -euo pipefail

IN="${1:?usage: mkbootlogo.sh <input-image> [output-header]}"
OUT="${2:-include/display/BootLogo.h}"
SYMBOL="BOOT_LOGO_RGB565"
WIDTH=240
HEIGHT=240

RAW="$(mktemp -t mkbootlogo.XXXXXX.rgb)"
trap 'rm -f "$RAW"' EXIT

# Aspect-fill to 240x240 with center crop (no distortion), honour EXIF rotation,
# flatten any transparency onto black, emit raw 8-bit RGB to a temp file.
magick "$IN" -auto-orient -resize "${WIDTH}x${HEIGHT}^" -gravity center \
    -extent "${WIDTH}x${HEIGHT}" -background black -alpha remove -alpha off \
    -depth 8 "RGB:$RAW"

python3 - "$OUT" "$SYMBOL" "$WIDTH" "$HEIGHT" "$RAW" <<'PY'
import sys

out_path, symbol, width, height, raw_path = sys.argv[1], sys.argv[2], int(sys.argv[3]), int(sys.argv[4]), sys.argv[5]
with open(raw_path, "rb") as rf:
    data = rf.read()
expected = width * height * 3
if len(data) != expected:
    sys.exit(f"unexpected RGB byte count: got {len(data)}, want {expected}")

words = []
for i in range(0, len(data), 3):
    r, g, b = data[i], data[i + 1], data[i + 2]
    words.append(((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3))

with open(out_path, "w") as f:
    f.write("// SPDX-License-Identifier: GPL-3.0-or-later\n")
    f.write("// Auto-generated by scripts/mkbootlogo.sh - do not edit by hand.\n")
    f.write("// 240x240 RGB565 boot splash.\n\n")
    f.write("#ifndef DISPLAY_BOOTLOGO_H\n#define DISPLAY_BOOTLOGO_H\n\n")
    f.write("#include <Arduino.h>\n")
    f.write('#include "config/ConfigManager.h"  // LCD_W, LCD_H\n\n')
    f.write(f"static const uint16_t {symbol}[LCD_W * LCD_H] PROGMEM = {{\n")
    for row in range(0, len(words), 12):
        chunk = ", ".join(f"0x{w:04X}" for w in words[row:row + 12])
        f.write(f"    {chunk},\n")
    f.write("};\n\n")
    f.write("#endif  // DISPLAY_BOOTLOGO_H\n")

print(f"wrote {out_path}: {len(words)} px ({symbol})")
PY
