#!/bin/bash
# Convert a PNG into a 240x240 RGB565 PROGMEM C header for the boot splash.
#
# Usage: scripts/png2rgb565.sh <input.png> <output.h> [SYMBOL_NAME]
#
# Requires: ImageMagick (magick), python3.
# Output: a header defining `static const uint16_t <SYMBOL>[LCD_W * LCD_H] PROGMEM = {...}`
# in standard RGB565 (R high), matching LCD_RED=0xF800 so draw16bitRGBBitmap needs no swap.

set -euo pipefail

IN="${1:?input png required}"
OUT="${2:?output header path required}"
SYMBOL="${3:-C64_LOGO_RGB565}"
WIDTH=240
HEIGHT=240

RAW="$(mktemp -t png2rgb565.XXXXXX.rgb)"
trap 'rm -f "$RAW"' EXIT

# Force exact size, flatten any transparency onto white, emit raw 8-bit RGB to a temp file.
magick "$IN" -resize "${WIDTH}x${HEIGHT}!" -background white -alpha remove -alpha off -depth 8 "RGB:$RAW"

python3 - "$OUT" "$SYMBOL" "$WIDTH" "$HEIGHT" "$RAW" <<'PY'
import sys

out_path, symbol, width, height, raw_path = sys.argv[1], sys.argv[2], int(sys.argv[3]), int(sys.argv[4]), sys.argv[5]
with open(raw_path, "rb") as rf:
    data = rf.read()
expected = width * height * 3
if len(data) != expected:
    sys.exit(f"unexpected RGB byte count: got {len(data)}, want {expected}")

words = []
for i in range(0, len(data), 3):
    r, g, b = data[i], data[i + 1], data[i + 2]
    words.append(((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3))

with open(out_path, "w") as f:
    f.write("// SPDX-License-Identifier: GPL-3.0-or-later\n")
    f.write("// Auto-generated by scripts/png2rgb565.sh - do not edit by hand.\n")
    f.write("// 240x240 RGB565 boot splash (Commodore logo).\n\n")
    f.write("#ifndef DISPLAY_C64LOGO_H\n#define DISPLAY_C64LOGO_H\n\n")
    f.write("#include <Arduino.h>\n")
    f.write('#include "config/ConfigManager.h"  // LCD_W, LCD_H\n\n')
    f.write(f"static const uint16_t {symbol}[LCD_W * LCD_H] PROGMEM = {{\n")
    for row in range(0, len(words), 12):
        chunk = ", ".join(f"0x{w:04X}" for w in words[row:row + 12])
        f.write(f"    {chunk},\n")
    f.write("};\n\n")
    f.write("#endif  // DISPLAY_C64LOGO_H\n")

print(f"wrote {out_path}: {len(words)} px ({symbol})")
PY
